services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stack-overflow-survey
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - postgres_data:/var/lib/postgresql/data

  postgres-airflow:
    image: postgres:latest
    container_name: postgres-airflow
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      
  airflow-init:
    image: apache/airflow:latest
    container_name: airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    depends_on:
      - postgres-airflow
    command: >
      bash -c "airflow db migrate"

  airflow-web:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-web
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW_CONN_MINIO_DEFAULT: 'aws://minioadmin:minioadmin@minio:9000'
      AIRFLOW__CORE__AUTH_MANAGER: airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:Admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/simple_auth_manager_passwords.json.generated
    volumes:
      - ./simple_auth_passwords.json:/opt/airflow/simple_auth_manager_passwords.json.generated
      - ./airflow/dags:/opt/airflow/dags
      - ./pyspark:/opt/pyspark
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-init
    command: >
      bash -c "
        until airflow db check; do
          echo 'waiting for airflow metadata DB…' && sleep 5;
        done &&
        airflow db migrate &&
        exec airflow api-server
      "
  
  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW_CONN_MINIO_DEFAULT: 'aws://minioadmin:minioadmin@minio:9000'
      AIRFLOW__CORE__AUTH_MANAGER: airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:Admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/simple_auth_manager_passwords.json.generated
    volumes:
      - ./simple_auth_passwords.json:/opt/airflow/simple_auth_manager_passwords.json.generated:ro
      - ./airflow/dags:/opt/airflow/dags
      - ./pyspark:/opt/pyspark
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-init
    command: scheduler

volumes:
  minio_data:
  postgres_data:
  pyspark:
    driver: local