services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - postgres_data:/var/lib/postgresql/data
      
  init-airflow:
    image: apache/airflow:latest
    container_name: init-airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/mydb
    depends_on:
      - postgres
      - minio
    command: >
      bash -c "airflow db init && 
               airflow db migrate && 
               airflow users create --username airflowadmin --password airflowadmin --firstname Admin --lastname User --role Admin --email admin@example.com"
  airflow_web:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow_web
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/mydb
      AIRFLOW_CONN_MINIO_DEFAULT: 'aws://minioadmin:minioadmin@minio:9000'
    volumes:
      - ./airflow:/opt/airflow
      - ./pyspark:/opt/pyspark
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - minio
      - postgres
      - init-airflow
    command: api-server
  
  airflow_scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/mydb
      AIRFLOW_CONN_MINIO_DEFAULT: 'aws://minioadmin:minioadmin@minio:9000'
    volumes:
      - ./airflow:/opt/airflow
      - ./pyspark:/opt/pyspark
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - minio
      - postgres
      - init-airflow
    command: scheduler

volumes:
  minio_data:
  postgres_data:
  pyspark:
    driver: local